export default {
	isDesktop: undefined,
	isTablet: 'tablet',
	isMobile: 'mobile',
	timeoutDebounce: 200,
	limit: 20,
	limitMobile: 6,
	usd: 'USD',
	cad: 'CAD',
	device: {
		created: 'CREATED',
		waitingForScan: 'WAITING_FOR_SCAN',
		waitingForApproval: 'WAITING_FOR_APPROVAL',
		posted: 'POSTED',
		inTransaction: "IN_TRANSACTION",
	},
	transaction: {
		created: 'CREATED',
		isScanned: 'IS_SCANNED',
		isScannedError: 'IS_SCANNED_ERROR',
		isBuyerScanned: 'IS_BUYER_SCANNED',
		submittedPasscode: 'SUBMIITED_PASSCODE',
		buyerAccept: 'BUYER_ACCEPT',
		buyerRejected: 'BUYER_REJECTED',
		systemCancelled: 'SYSTEM_CANCELLED'
	},
	proposal: {
		buyerCreated: 'BUYER_CREATED',
		buyerReply: 'BUYER_REPLY',
		buyerAccept: 'BUYER_ACCEPT',
		sellerReply: 'SELLER_REPLY',
		sellerAccept: 'SELLER_ACCEPT',
		sellerReject: 'SELLER_REJECT',
		buyerRemove: 'BUYER_REMOVED',
		sellerCancelAccept: 'SELLER_CANCEL_ACCEPT',
		systemCancelAccept: 'SYSTEM_CANCEL_ACCEPT',
		errProposalStillAccepted: 'ERR_PROPOSAL_STILL_ACCEPTED',
	},
	order: {
		created: 'CREATED',
		group: 'GROUP',
		ownerScanned: 'OWNER_SCANNED',
		buyerRejected: 'BUYER_REJECTED',
		buyerAccept: 'BUYER_ACCEPT',
		pending: 'PENDING',
		waitingForDevicePayment: 'WAITING_FOR_DEVICE_PAYMENT',
		waitingForOwnerPayment: 'WAITING_FOR_OWNER_PAYMENT',
		devicePayment: "DEVICE_PAYMENT",
		processing: "PROCESSING",
		processTransaction: "PROCESS_TRANSACTION",
		shipped: "SHIPPED",
		completed: "COMPLETED",
		buyerReceived: "BUYER_RECEIVED",
		confirm: "CONFIRM",
		inDispute: "IN_DISPUTE",
		ready: "READY",
		toBeShipped: "TO_BE_SHIPPED",
		delivered: "DELIVERED",
		systemCancelNotPayShip: "SYSTEM_CANCELLED_NOT_PAY_SHIP"
	},
	exchangeType: {
		request: 'request',
		offer: 'offer',
	},
	containerDesktop: 1200,
	nothave: 'nothave',
	yes: 'y',
	no: 'n',
	unknown: 'un',
	idCart: 'id-cart',
	sell: 'sell',
	exchange: 'exchange',
	buyer: 'BUYER',
	seller: 'SELLER',
	notOriginal: 'notOriginal',
	original: 'original',
	optionsTutorialScanQrCode: {
		width: 180,
		height: 390,
	},
	noAccessories: 'server.noAccessories',
	socketNotificationClient: 'notification-client',
	proposalBuyer: 'PROPOSAL_BUYER',
	proposalSeller: 'PROPOSAL_SELLER',
	notificationOrder: 'order',
	dingtoiProAppPosted: 'DINGTOI_PRO_APP_POSTED',
	passwordNotCorrect: 'PASSWORD_NOT_CORRECT',
	buyerAcceptedTime: 'buyer_accepted_time',
	sellerAcceptedTime: 'seller_accepted_time',
	sellerCancelAcceptedTime: "seller_accept_proposal_time",
	timer: "timer",
	shippoToken: 'shippo_test_ab805d3728348a325c1b567938369aca77372d69',
	domainShippo: 'https://api.goshippo.com/',
	canadaPostAddressCompleteToken: 'XK45-PG26-DG79-CZ32',
	domainCanadaPostAddressComplete: 'http://ws1.postescanada-canadapost.ca/AddressComplete/Interactive/',
	deviceMobile: {
		height: 0.29,
		width: 3.07,
		length: 6.33,
		weight: 0.5,
		mass_unit: 'lb',
		distance_unit: 'in'
	},
	payment: {
		errorNumber: 'Your card number is incorrect.',
		errorExpYear: "Your card's expiration year is invalid.",
		errorExpMonth: "Your card's expiration month is invalid.",
		errorCvc: "Your card's security code is invalid."
	},
	notification: {
		transaction: 'TRANSACTION',
		timerTransaction: 'TIMER_TRANSACTION',
		transactionStarted: 'STARTED',
		purchase: "PURCHASE",
		sale: "SALE",
		timerOrderSeller: "TIMER_ORDER_SELLER"

	},
	selectedCountry: 1,
	appStore: 'https://apps.apple.com/ca/app/id1524735381',
	googlePlay: 'https://play.google.com/store/apps/details?id=com.dingtoi.dingtoimc',
	TRANSACTION_PROCESS_STATUS: {
		LOGIN: 'TRANSACTION_PROCESS_LOGIN',
	},
	transactionProcess: 'TRANSACTION_PROCESS',
	transactionProcessQrCode: "TRANSACTION_PROCESS_QR_CODE",
	buildingLocationType: [
		{ value: 'front_door', name: 'Front Door' },
		{ value: 'back_door', name: 'Back Door' },
		{ value: 'side_door', name: 'Side Door' },
		{ value: 'knock_on_door', name: 'Knock on Door' },
		{ value: 'ring_bell', name: 'Ring Bell' },
		{ value: 'mail_room', name: 'Mail Room' },
		{ value: 'office', name: 'Office' },
		{ value: 'reception', name: 'Reception' },
		{ value: 'in_at_mailbox', name: 'In/At Mailbox' },
		{ value: 'security_deck', name: 'Security Deck' },
		{ value: 'shipping_dock', name: 'Shipping Dock' },
		{ value: 'other', name: 'Other' },
	],
	buildingType: [
		{ value: 'apartment', name: 'Apartment' },
		{ value: 'building', name: 'Building' },
		{ value: 'department', name: 'Department' },
		{ value: 'floor', name: 'Floor' },
		{ value: 'room', name: 'Room' },
		{ value: 'suite', name: 'Suite' },
	],

	groupGeneral: [
		{ key: 'touchscreen', label: 'touch screen' },
		{ key: 'camera', label: 'camera' },
		{ key: 'flash', label: 'flash' },
		{ key: 'volume', label: 'volume' },
		{ key: 'volume', label: 'speaker' },
		{ key: 'microphone', label: 'microphone' },
		{ key: 'finger', label: 'finger' },
	],
	groupConnection: [
		{ key: 'wifi', label: 'wifi' },
		{ key: 'bluetooth', label: 'bluetooth' },
	],
	groupPhone: [
		{ key: 'voiceInbound', label: 'Voice Inbound' },
		{ key: 'voiceOutbound', label: 'Voice Outbound' },
	],
	groupSMS: [
		{ key: 'textInbound', label: 'SMS Inbound' },
		{ key: 'textOutbound', label: 'SMS Outbound' },
	],
};
